-- MySQL Script generated by MySQL Workbench
-- dim. 08 nov. 2020 21:29:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document` (
  `id_document` INT NOT NULL,
  `name` TEXT NULL,
  `url` TEXT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id_document`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`word` (
  `id_word` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id_word`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`occurrence_word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`occurrence_word` (
  `id_occurrence_word` INT NOT NULL,
  `number` INT NULL,
  `word_id_word` INT NOT NULL,
  PRIMARY KEY (`id_occurrence_word`, `word_id_word`),
  INDEX `fk_occurrence_word_word1_idx` (`word_id_word` ASC) VISIBLE,
  CONSTRAINT `fk_occurrence_word_word1`
    FOREIGN KEY (`word_id_word`)
    REFERENCES `mydb`.`word` (`id_word`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`document_occurence_word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document_occurence_word` (
  `iddocument_occurence_word` INT NOT NULL,
  `document_id_document` INT NOT NULL,
  `list_id_occurrence_word` TEXT NOT NULL,
  PRIMARY KEY (`iddocument_occurence_word`, `document_id_document`),
  INDEX `fk_document_occurence_word_document1_idx` (`document_id_document` ASC) VISIBLE,
  INDEX `fk_document_occurence_word_occurrence_word1_idx` (`list_id_occurrence_word` ASC) VISIBLE,
  CONSTRAINT `fk_document_occurence_word_document1`
    FOREIGN KEY (`document_id_document`)
    REFERENCES `mydb`.`document` (`id_document`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_occurence_word_occurrence_word1`
    FOREIGN KEY (`list_id_occurrence_word`)
    REFERENCES `mydb`.`occurrence_word` (`id_occurrence_word`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
