-- MySQL Script generated by MySQL Workbench
-- lun. 09 nov. 2020 02:34:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_database` ;
USE `my_database` ;

-- -----------------------------------------------------
-- Table `my_database`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_database`.`document` (
  `id_document` INT NOT NULL,
  `name` TEXT NULL,
  `url` TEXT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id_document`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_database`.`word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_database`.`word` (
  `id_word` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id_word`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_database`.`document_occurence_word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_database`.`document_occurence_word` (
  `iddocument_occurence_word` INT NOT NULL,
  `document_id_document` INT NOT NULL,
  PRIMARY KEY (`iddocument_occurence_word`, `document_id_document`),
  INDEX `fk_document_occurence_word_document1_idx` (`document_id_document` ASC) VISIBLE,
  CONSTRAINT `fk_document_occurence_word_document1`
    FOREIGN KEY (`document_id_document`)
    REFERENCES `my_database`.`document` (`id_document`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_database`.`occurrence_word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_database`.`occurrence_word` (
  `id_occurrence_word` INT NOT NULL,
  `number` INT NULL,
  `word_id_word` INT NOT NULL,
  PRIMARY KEY (`id_occurrence_word`, `word_id_word`),
  INDEX `fk_occurrence_word_word1_idx` (`word_id_word` ASC) VISIBLE,
  CONSTRAINT `fk_occurrence_word_word1`
    FOREIGN KEY (`word_id_word`)
    REFERENCES `my_database`.`word` (`id_word`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
