-- MySQL Script generated by MySQL Workbench
-- dim. 15 nov. 2020 23:53:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema index_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema index_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `index_database` ;
USE `index_database` ;

-- -----------------------------------------------------
-- Table `index_database`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index_database`.`document` (
  `id_document` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `chemin` TEXT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id_document`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `index_database`.`word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index_database`.`word` (
  `id_word` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id_word`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `index_database`.`occurrence_word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index_database`.`occurrence_word` (
  `number` INT NULL,
  `id_word` INT NOT NULL,
  `id_document` INT NOT NULL,
  PRIMARY KEY (`id_word`, `id_document`),
  INDEX `fk_occurrence_word_word1_idx` (`id_word` ASC) ,
  INDEX `fk_occurrence_word_document1_idx` (`id_document` ASC) ,
  CONSTRAINT `fk_occurrence_word_word1`
    FOREIGN KEY (`id_word`)
    REFERENCES `index_database`.`word` (`id_word`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_occurrence_word_document1`
    FOREIGN KEY (`id_document`)
    REFERENCES `index_database`.`document` (`id_document`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
