DROP TABLE IF EXISTS document_mot;
DROP TABLE IF EXISTS document;
DROP TABLE IF EXISTS mot;
-- MySQL Script generated by MySQL Workbench
-- lun. 23 nov. 2020 13:46:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdd_tiw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_tiw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_tiw` ;
USE `bdd_tiw` ;

-- -----------------------------------------------------
-- Table `bdd_tiw`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_tiw`.`document` (
  `id_document` INT NOT NULL AUTO_INCREMENT,
  `titre` TEXT NULL,
  `path` TEXT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id_document`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_tiw`.`mot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_tiw`.`mot` (
  `id_mot` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  `label_order` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_tiw`.`document_mot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_tiw`.`document_mot` (
  `poid` FLOAT NULL,
  `id_mot` INT NOT NULL,
  `id_document` INT NOT NULL,
  PRIMARY KEY (`id_mot`, `id_document`),
  INDEX `fk_occurrence_mot_mot1_idx` (`id_mot` ASC),
  INDEX `fk_occurrence_mot_document1_idx` (`id_document` ASC),
  CONSTRAINT `fk_occurrence_mot_mot1`
    FOREIGN KEY (`id_mot`)
    REFERENCES `bdd_tiw`.`mot` (`id_mot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_occurrence_mot_document1`
    FOREIGN KEY (`id_document`)
    REFERENCES `bdd_tiw`.`document` (`id_document`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
